# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/material/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

# ----------------------------------------------
# CRY Settings
# ----------------------------------------------

/control/execute Cry.mac

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize
/rlt/SetFileName root_file/CryMu.root
/run/printProgress 1000
/run/beamOn 100000
