# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/tracking/verbose 0
/event/verbose 0
/gps/verbose 0

# ----------------------------------------------
# General Particle Source (GPS) Settings
# ----------------------------------------------

/control/execute CryMuGps.mac

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize

# Number of beams generated
/rlt/SetFileName root_file/CryMu.root
/run/printProgress 1000
/run/beamOn 100000
