# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/tracking/verbose 0
/event/verbose 0
/gps/verbose 0

# ----------------------------------------------
# General Particle Source (GPS) Settings
# ----------------------------------------------

/control/execute CryMuGps.mac

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize
/rlt/SetFileName root_file/CryMu.root
/camera/enable
/run/printProgress 1
/run/beamOn 1
