# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/gps/verbose 0
/material/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

# ----------------------------------------------
# General Particle Source (GPS) Settings
# ----------------------------------------------

/control/execute CryMuGps.mac

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize
/rlt/SetFileName root_file/CryMu.root
/run/printProgress 1000
/run/beamOn 100000
