# Schema
schema: volume_schema.yaml

---

newrpc_xy_readout_plate:
  solid: box
  x: &newrpc_readout_plate_x 300 mm
  y: &newrpc_readout_plate_y 300 mm
  z: &newrpc_xy_readout_plate_z 0.4 mm
  material: newrpc_fr4

newrpc_xy_readout_plate_box:  # This centers the plate.
  solid: bottom_up
  components: [newrpc_xy_readout_plate]
  x: *newrpc_readout_plate_x
  y: &newrpc_readout_plate_box_y 350 mm
  z: *newrpc_xy_readout_plate_z
  offset: [0, -12.5 mm, 0]
  material: newrpc_gas

newrpc_t_readout_plate:
  solid: box
  x: *newrpc_readout_plate_x
  y: *newrpc_readout_plate_y
  z: &newrpc_t_readout_plate_z 1.565 mm
  material: newrpc_fr4

newrpc_t_readout_plate_box:  # This centers the plate.
  solid: bottom_up
  components: [newrpc_t_readout_plate]
  x: *newrpc_readout_plate_x
  y: *newrpc_readout_plate_box_y
  z: *newrpc_t_readout_plate_z
  offset: [0, -12.5 mm, 0]
  material: newrpc_gas

newrpc_readout_bar:
  solid: box
  x: 2.0 mm
  y: &newrpc_readout_bar_y 200 mm
  z: &newrpc_readout_bar_z 0.1 mm
  material: newrpc_readout_bar

newrpc_readout_gas:
  solid: box
  x: 0.27 mm
  y: *newrpc_readout_bar_y
  z: *newrpc_readout_bar_z
  material: newrpc_gas

newrpc_readout_bars:
  solid: left_right
  components:
    - newrpc_readout_gas
    - newrpc_readout_bar
    - newrpc_readout_gas
  duplicate: 80
  material: newrpc_gas

newrpc_xy_readout_bars:
  solid: rotation
  components: [newrpc_readout_bars]

newrpc_xy_readout_board:
  solid: bottom_up
  components:
    - newrpc_xy_readout_plate
    - newrpc_xy_readout_bars
  material: newrpc_gas

newrpc_t_readout_cu:
  solid: box
  x: 280 mm
  y: 280 mm
  z: 35 um
  material: newrpc_readout_cu

newrpc_t_readout_board:
  solid: bottom_up
  components:
    - newrpc_t_readout_plate
    - newrpc_t_readout_cu
  material: newrpc_gas

---

# Comments
materials:
  - newrpc_fr4
  - newrpc_gas
  - newrpc_readout_bar
  - newrpc_readout_cu
